In [13]:
import numpy as np
from numpy import array
import scipy as scp
from scipy.linalg import svd

A = array([[-1.32, -0.18, 2.13], [2.64, -4.68, 4.65] , [1.47, -4.75,6.80] ])

print(A)


[[-1.32 -0.18  2.13]
 [ 2.64 -4.68  4.65]
 [ 1.47 -4.75  6.8 ]]


In [17]:
U, s, VT = svd(A)
print("U=",U)
print()
print("s=",s)
print()
print(VT)
print()

U= [[ 0.1288709  -0.81535465 -0.56443697]
 [ 0.63455281  0.50520086 -0.58490583]
 [ 0.76205973 -0.28278772  0.58249127]]

s= [11.01365384  2.54146561  0.09990768]

[[ 0.23837118 -0.60040816  0.76334083]
 [ 0.78470487 -0.34402767 -0.51563866]
 [ 0.57220403  0.72191066  0.38913692]]

